#!/bin/sh
#
# 2014 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

file=$(cat "${__object}/parameter/file")

# extract the keytype and base64 encoded key ignoring any options and comment
type_and_key=$(sed -e 's/#.*$//' "${__object}/parameter/key" | grep -o '\(ssh\|ecdsa\)-[^ ]\{1,\} [A-Za-z0-9+/=]\{1,\}')

# If $type_and_key is empty, which is the case with an invalid key, do not grep
# $file because it results in grepping everything in file and all entries from
# file are removed.
if test -r "${file}" -a -n "${type_and_key}"
then
    # get any entries that match the type and key

    # NOTE: Do not match from the beginning of the line as there may be options
    # preceeding the key.
    grep "${type_and_key}"'\([ \n].*\)*$' "${file}" || true
fi
