#!/bin/sh
#
# 2014 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

if [ -f "$__object/parameter/file" ]; then
   cat "$__object/parameter/file"
else
   owner="$(cat "$__object/parameter/owner" 2>/dev/null || echo "$__object_id")"

   if command -v getent
   then
      owner_line=$(getent passwd "$owner")
   else
      case "$owner"
      in
         [0-9][0-9]*)
            owner_line="$(grep "^[^:]*:[^:]*:$owner:" /etc/passwd)"
            ;;
         *)
            owner_line="$(grep "^$owner" /etc/passwd)"
            ;;
      esac
   fi

   home="$(echo "$owner_line" | cut -d':' -f 6)"
   echo "$home/.ssh/authorized_keys"
fi
