#!/bin/sh
#
# 2013 Steven Armstrong (steven-cdist armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

destination="/$__object_id"

# nothing to work with, nothing we could do
[ -e "$destination" ] || exit 0

if command -v stat
then
	os=$("$__explorer/os")
	case "$os" in
		"freebsd"|"netbsd"|"openbsd")
			# FIXME: should be something like this based on man page, but can not test
			stat -f "type: %ST
owner: %Du %Su
group: %Dg %Sg
mode: %Op %Sp
" "$destination"
			;;
		"macosx")
			stat -f "type: %HT
owner: %Du %Su
group: %Dg %Sg
mode: %Lp %Sp
" "$destination"
			;;
		*)
			stat --printf="type: %F
owner: %u %U
group: %g %G
mode: %a %A
" "$destination"
			;;
	esac
else
	# Patch the output together, manually

	uid="$(ls -ln "$destination" | awk '{ print $3 }')"
	gid="$(ls -ln "$destination" | awk '{ print $4 }')"

	owner="$(grep "^[^:]*:[^:]*:$uid:" /etc/passwd | cut -d':' -f 1 || echo UNKNOWN)"
	group="$(grep "^[^:]*:[^:]*:$uid:" /etc/group | cut -d':' -f 1 || echo UNKNOWN)"

	mode_text="$(ls -ln "$destination" | awk '{ print $1 }')"
	mode="$(echo "$mode_text" | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));printf("%0o",k)}')"

	printf 'type: %s
owner: %s %s
group: %s %s
mode: %s %s
' \
	"$("$__type_explorer/type")" \
	"$uid" "$owner" \
	"$gid" "$group" \
	"$mode" "$mode_text"
fi
